// One short, embeddable how-to video per move (key matches DEMOS). Picked for clear form demos from
// physical therapists, hospitals and coaching channels; all verified embeddable 2026-10-07.
export const VIDEOS: Record<string, { id: string; title: string; channel: string }> = {
  march: { id: 'u1gmWFvEluM', title: "Marching in Place Demonstrated by a Physical Therapist", channel: "Margaret Martin, Physical Therapist" },
  armCircles: { id: 'Lha66p0ZXUc', title: "How to Do:ARM CIRCLES", channel: "Leap Fitness" },
  hipCircles: { id: 'JYqLwajOGjI', title: "Hip Circles Tutorial - Proper Form and Technique", channel: "Runna" },
  torsoTwist: { id: 'I5YbtdqK6g0', title: "How To: Standing Oblique Twists with Just Hands", channel: "ScottHermanFitness" },
  jacks: { id: 'nGaXj3kkmrU', title: "How to Do Jumping Jacks Properly", channel: "Babylon" },
  jacks_low: { id: 'p75NmUtH9so', title: "How to Do:SIDE STEP JACKS", channel: "Leap Fitness" },
  highKnees: { id: 'ZZZoCNMU48U', title: "High Knees (Lv 2)", channel: "FitnessBlender" },
  highKnees_low: { id: '0Nmk00-YWiY', title: "Standing Knee Raises", channel: "99 Walks" },
  buttKicks: { id: 'oMW59TKZvaI', title: "How to Butt-Kick with Proper Form", channel: "Get Healthy U - with Chris Freytag" },
  buttKicks_low: { id: 'LaDKpYN9FDw', title: "Standing Hamstring Curls", channel: "Baptist Health" },
  skaters: { id: 'Jx2KXGbQkYM', title: "How To Do Skaters", channel: "Get Healthy U - with Chris Freytag" },
  skaters_low: { id: 'af0j7vHXlEM', title: "iMpuls: Side Step and Reach", channel: "iMpuls" },
  climbers: { id: 'cnyTQDSE884', title: "How to Do Mountain Climbers | The Right Way | Well+Good", channel: "Well+Good" },
  climbers_low: { id: 'OuR8FqNX5_4', title: "Incline mountain climber on chair for  men", channel: "Pro Gym Workout" },
  burpee: { id: 'NCqbpkoiyXE', title: "How To Burpee | Nuffield Health", channel: "Nuffield Health" },
  burpee_low: { id: 'LTaZU3yIOGE', title: "Step-back Burpees", channel: "Brian DeBaets" },
  squatJump: { id: 'BRfxI2Es2lE', title: "How To Jump Squat", channel: "PureGym" },
  squatJump_low: { id: 'Hcy81KUTIZ8', title: "How to Do:SUMO SQUAT CALF RAISES WITH WALL", channel: "Leap Fitness" },
  punches: { id: 'J4j3AOVWuHE', title: "Quick Shadow Boxing Tutorial by Olympian", channel: "Tony Jeffries" },
  squat: { id: 'm0GcZ24pK6k', title: "How to do a body weight squat", channel: "Bupa Health" },
  squat_low: { id: 'ITv-_BkcrD0', title: "Sit to Stand", channel: "Baptist Health" },
  pushup: { id: 'WDIpL0pjun0', title: "How to do a Push-Up | Proper Form & Technique | NASM", channel: "National Academy of Sports Medicine (NASM)" },
  pushup_low: { id: 'wIPJvBQs7RA', title: "How to Do Wall Push Ups: A Guide from Physical Therapists", channel: "Hinge Health" },
  lunge: { id: 'xrPteyQLGAo', title: "How To Reverse Lunge", channel: "PureGym" },
  lunge_low: { id: 'vUikQQsXCbg', title: "How to do a Split Squat Supported", channel: "Rehab My Patient" },
  bridge: { id: 'sh63qy5EV_8', title: "Glute Bridge Exercise Demo", channel: "Redefined Health" },
  plank: { id: 'pvIjsG5Svck', title: "Core Exercise: Plank", channel: "Children's Hospital Colorado" },
  plank_low: { id: 's42Km3PWHKA', title: "1-Minute Core Strength | Countertop Planks for Beginner Core and Abs | MS Exercise Snacks", channel: "Can Do Multiple Sclerosis" },
  superman: { id: 'J9zXkxUAfUA', title: "Core Exercise: Superman", channel: "Children's Hospital Colorado" },
  superman_low: { id: 'xEDnlOxeJH4', title: "How to Do the Bird Dog Exercise: A Guide from Physical Therapists", channel: "Hinge Health" },
  dips: { id: 'p_yzmkwz5JA', title: "Deskercise - Chair Dips", channel: "HealthyLivingMo" },
  dips_low: { id: 'Y-zpMnf8-Ms', title: "How To Do Chair Dips With Bent Knees", channel: "Calixpert" },
  calfRaise: { id: 'eMTy3qylqnE', title: "Calf Raise Exercise Demo", channel: "Redefined Health" },
  wallSit: { id: 'JaZNYM3zAP0', title: "How To Do a Wall Sit | The Right Way | Well+Good", channel: "Well+Good" },
  wallSit_low: { id: 'cWTZ8Am1Ee0', title: "How to Do a Wall Sit Exercise | 30 Seconds | MedBridge", channel: "Medbridge" },
  sidePlank: { id: 'N_s9em1xTqU', title: "Core Exercise: Side Plank", channel: "Children's Hospital Colorado" },
  sidePlank_low: { id: '-Dw9Es42eLM', title: "Side plank on knee", channel: "Alpine Physical Therapy Home Exercises" },
  catCow: { id: 'vuyUwtHl694', title: "Cat Cow", channel: "California Department of Public Health" },
  birdDog: { id: 'xEDnlOxeJH4', title: "How to Do the Bird Dog Exercise: A Guide from Physical Therapists", channel: "Hinge Health" },
  deadBug: { id: 'GbSC02oU3To', title: "How to Do a Dead Bug: A Guide from Physical Therapists", channel: "Hinge Health" },
  clamshell: { id: 'EG5_gXcfozw', title: "How To Do The Clamshell Exercise - Kinetic Sports Rehab", channel: "Tangelo - Seattle Chiropractor + Rehab" },
  wallAngel: { id: '1UU4VvklQ44', title: "How to Perform Wall Angel for Tight Upper Back", channel: "Vive Health" },
  heelSlide: { id: '6-anByqnKp8', title: "Core Exercise: Heel Slide", channel: "Children's Hospital Colorado" },
  legExt: { id: 'VuJZ6dqMf8M', title: "Seated Knee Extension (LAQ)", channel: "AskDoctorJo" },
  shoulderRoll: { id: 'IKJZL4hvppw', title: "Shoulder Rolls", channel: "Coury & Buehler Physical Therapy" },
  hinge: { id: '2W_gXhut5S8', title: "How to Do a Hip Hinge: A Guide from Physical Therapists", channel: "Hinge Health" },
  hipFlexor: { id: 'bnVfloe6yTo', title: "Half Kneeling Hip Flexor Stretch", channel: "Pursuit Fitness" },
  hipFlexor_low: { id: 'ljCDEb_MIto', title: "Hip Flexor Stretch-Standing", channel: "Coury & Buehler Physical Therapy" },
  worldsGreatest: { id: 'BHlTY6K7uNg', title: "Lunge with Reach | 24 Hour Fitness", channel: "24 Hour Fitness" },
  worldsGreatest_low: { id: 'BHlTY6K7uNg', title: "Lunge with Reach | 24 Hour Fitness", channel: "24 Hour Fitness" },
  openBook: { id: 'OW6YHlxY6JI', title: "Open Book Stretch - Physical Therapy Exercises", channel: "TSAOG Orthopaedics & Spine" },
  ankleCircles: { id: 'mzTQGYGI0Ng', title: "Ankle Circles - Ask Doctor Jo", channel: "AskDoctorJo" },
  squatHold: { id: 'IHApHfNA2Ag', title: "How to Do a Deep Squat According to Physical Therapists", channel: "Hinge Health" },
  squatHold_low: { id: 'uQbUORRwzqk', title: "How to do a Supported Deep Squat Hold", channel: "Get Strong with Emily" },
  hamSweep: { id: 'q8cNk-WNQa8', title: "Hamstring sweeps", channel: "freedomfitness" },
  forwardFold: { id: 'SLIaql7h6RQ', title: "Forward Fold Yoga Pose - Seated and Standing", channel: "Vive Health" },
  forwardFold_low: { id: 'QRIKGOUJILs', title: "Seated Forward Bend Chair Stretch", channel: "Vive Health" },
  chestOpen: { id: '16qCwSMGqx4', title: "Chest Opener Stretch", channel: "PALM Health" },
  breathe: { id: 'tEmt1Znux58', title: "Box breathing relaxation technique: how to calm feelings of stress or anxiety", channel: "Sunnybrook Hospital" },
};
